### ISSUE TITLE
Webhooks subscription not working properly

### ISSUE THREAD

**Issue by Thura98** [hubplanner/API#70]
When I tried to create a webhook subscription and tried to get a json response from the post method, I did not get the subscription I created and instead, I got a JSONDecodeError: Expecting value: error instead. When I tried to create a subscription without trying to get a json response, multiple webhooks subscriptions were created when I only wanted to create a single subscription.

**Comment by fikatown** [comment]
This could be various things which can happen here. You should make sure to do the following:

- for successful subscription POST {{api_url}}/subscription with request body as follows:

```{
    "event": "booking.create" // event in hubplanner they want to subscribe to.
    "target_url": "their public endpoint to receive data from webhooks"
}```

Headers of the request should be set as follows:

```Content-Type: application/json
Accept: application/json
Authorization: {{api_token}} // read-write
User-Agent: name (email) // optional```

Before creating subscription with request as above, make sure that the endpoint from "target_url" is reachable (public). We provide `connectionStatus` field in subscription response to notify if this endpoint is reachable from us or there is any trouble. After subscribing, with every triggered operation on your account (identified by api key) in Hub Planner you subscribed to, data is sent to your target_url in the form of: [ {JSON_OBJECT} ]. Make sure you count those [] array incoming, not just parse JSON right away from response.

**Comment by Thura98** [comment]
Yes, I know about that, I am using ngrok as a secure tunnel to my localhost, so that I can connect to hubplanner.

**Comment by Thura98** [comment]
> {'message': 'URL is not correctly formatted - http://127.0.0.1:8000/webhookstest/', 'error': 'SUBSCRIPTION_TARGET_URL_INCORRECT', 'code': 'WH_SUB_URL_ERROR', 'properties': {'additionalInformation': {'incorrectURL': 'http://127.0.0.1:8000/webhookstest/'}}, 'version': 2}]

I am just using this to show that only when my endpoint is not reachable, the subscription would be printed out on my console, but when I created a secure tunnel to my localhost and the endpoint is reachable, I am unable to print out the subscription on my console. 

> Internal Server Error: /webhookstest/
Traceback (most recent call last):
File "/home/thura98/django_projects/CenturionBooker_VirtualEnv2/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/home/thura98/django_projects/CenturionBooker_VirtualEnv2/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/home/thura98/django_projects/CenturionBooker_VirtualEnv2/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/thura98/django_projects/CenturionBooker_VirtualEnv2/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
return view_func(*args, **kwargs)
File "/home/thura98/django_projects/webhooks_testprj2/myapp/views.py", line 12, in webhooktest
print(HubplannerWebHookSuscribe("resource.update"))
File "/home/thura98/django_projects/webhooks_testprj2/myapp/views.py", line 35, in HubplannerWebHookSuscribe
return HubplannerResponse.json()
File "/home/thura98/django_projects/CenturionBooker_VirtualEnv2/lib/python3.6/site-packages/requests/models.py", line 896, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib/python3.6/json/init.py", line 354, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[02/Aug/2018 15:53:07] "POST /webhookstest/ HTTP/1.1" 500 119997
Internal Server Error: /webhookstest/
Traceback (most recent call last):
File "/home/thura98/django_projects/CenturionBooker_VirtualEnv2/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
response = get_response(request)
File "/home/thura98/django_projects/CenturionBooker_VirtualEnv2/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/home/thura98/django_projects/CenturionBooker_VirtualEnv2/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/thura98/django_projects/CenturionBooker_VirtualEnv2/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
return view_func(*args, **kwargs)
File "/home/thura98/django_projects/webhooks_testprj2/myapp/views.py", line 12, in webhooktest
print(HubplannerWebHookSuscribe("resource.update"))
File "/home/thura98/django_projects/webhooks_testprj2/myapp/views.py", line 35, in HubplannerWebHookSuscribe
return HubplannerResponse.json()
File "/home/thura98/django_projects/CenturionBooker_VirtualEnv2/lib/python3.6/site-packages/requests/models.py", line 896, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/lib/python3.6/json/init.py", line 354, in loads
return _default_decoder.decode(s)
File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above error is shown once I have created a an endpoint that is reachable through a secure tunnel to my localhost and I am unable to print out the subscription on my console. Is it alright if you can check to see if the webhooks are working fine? @fikatown

**Comment by fikatown** [comment]
I am not sure how the tunnel would work for you, web hooks are definitely working so they are not the 
 issue. You should be given some public address like http://some-address.com . From the perspective of our server your 127.0.0.1 address will point to our machine itself, not to you, 127.0.0.1 is loopback address. Maybe try push to some staging environment where you can have an endpoint that is accessible.
